#!/usr/bin/env python
# -*- coding: utf-8 -*-
TABLERONAME = 'CINESUR EL TABLERO 3D'
GUADALQUIVIRNAME = 'GUADALQUIVIR CINEMAS 10 3D'
LUCENANAME = 'ARTESIETE LUCENA'
SANANDRESNAME = 'COLISEO SAN ANDRÉS'
DELICIASNAME = 'DELICIAS'
OLIMPIANAME = 'OLIMPIA'
FUENSECANAME = 'FUENSECA'
PLAZADETOROSNAME = 'PLAZA DE TOROS'
CARTELERANAME = 'http://www.carteleracordoba.com/'
IMDBTITLE = 'www.imdb.com/title/tt'